/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum CityVotingProblems {
  CVP_CRIME,
  CVP_POLLUTION,
  CVP_HOUSING,
  CVP_TAXES,
  CVP_TRAFFIC,
  CVP_UNEMPLOYMENT,
  CVP_FIRE,
  CVP_NUMPROBLEMS,
  CVP_PROBLEM_COMPLAINTS = 4,
  PROBNUM = 10
}
