/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum HistoryType {
  HISTORY_TYPE_RES,
  HISTORY_TYPE_COM,
  HISTORY_TYPE_IND,
  HISTORY_TYPE_MONEY,
  HISTORY_TYPE_CRIME,
  HISTORY_TYPE_POLLUTION,
  HISTORY_TYPE_COUNT
}
