/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum HistoryScale {
  HISTORY_SCALE_SHORT,
  HISTORY_SCALE_LONG,
  HISTORY_SCALE_COUNT
}
