/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class MapByte1 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MapByte1(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MapByte1 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MapByte1() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          micropolisenginePINVOKE.delete_MapByte1(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public MapByte1(byte defaultValue) : this(micropolisenginePINVOKE.new_MapByte1__SWIG_0(defaultValue), true) {
  }

  public MapByte1(MapByte1 map) : this(micropolisenginePINVOKE.new_MapByte1__SWIG_1(MapByte1.getCPtr(map)), true) {
    if (micropolisenginePINVOKE.SWIGPendingException.Pending) throw micropolisenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int MAP_BLOCKSIZE {
    get {
      int ret = micropolisenginePINVOKE.MapByte1_MAP_BLOCKSIZE_get(swigCPtr);
      return ret;
    } 
  }

  public int MAP_W {
    get {
      int ret = micropolisenginePINVOKE.MapByte1_MAP_W_get(swigCPtr);
      return ret;
    } 
  }

  public int MAP_H {
    get {
      int ret = micropolisenginePINVOKE.MapByte1_MAP_H_get(swigCPtr);
      return ret;
    } 
  }

  public void fill(byte val) {
    micropolisenginePINVOKE.MapByte1_fill(swigCPtr, val);
  }

  public void clear() {
    micropolisenginePINVOKE.MapByte1_clear(swigCPtr);
  }

  public void set(int x, int y, byte val) {
    micropolisenginePINVOKE.MapByte1_set(swigCPtr, x, y, val);
  }

  public byte get(int x, int y) {
    byte ret = micropolisenginePINVOKE.MapByte1_get(swigCPtr, x, y);
    return ret;
  }

  public bool onMap(int x, int y) {
    bool ret = micropolisenginePINVOKE.MapByte1_onMap(swigCPtr, x, y);
    return ret;
  }

  public void worldSet(int x, int y, byte val) {
    micropolisenginePINVOKE.MapByte1_worldSet(swigCPtr, x, y, val);
  }

  public byte worldGet(int x, int y) {
    byte ret = micropolisenginePINVOKE.MapByte1_worldGet(swigCPtr, x, y);
    return ret;
  }

  public bool worldOnMap(int x, int y) {
    bool ret = micropolisenginePINVOKE.MapByte1_worldOnMap(swigCPtr, x, y);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char getBase() {
    IntPtr cPtr = micropolisenginePINVOKE.MapByte1_getBase(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

}
