/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class MapShort8 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MapShort8(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MapShort8 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MapShort8() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          micropolisenginePINVOKE.delete_MapShort8(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public MapShort8(short defaultValue) : this(micropolisenginePINVOKE.new_MapShort8__SWIG_0(defaultValue), true) {
  }

  public MapShort8(MapShort8 map) : this(micropolisenginePINVOKE.new_MapShort8__SWIG_1(MapShort8.getCPtr(map)), true) {
    if (micropolisenginePINVOKE.SWIGPendingException.Pending) throw micropolisenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int MAP_BLOCKSIZE {
    get {
      int ret = micropolisenginePINVOKE.MapShort8_MAP_BLOCKSIZE_get(swigCPtr);
      return ret;
    } 
  }

  public int MAP_W {
    get {
      int ret = micropolisenginePINVOKE.MapShort8_MAP_W_get(swigCPtr);
      return ret;
    } 
  }

  public int MAP_H {
    get {
      int ret = micropolisenginePINVOKE.MapShort8_MAP_H_get(swigCPtr);
      return ret;
    } 
  }

  public void fill(short val) {
    micropolisenginePINVOKE.MapShort8_fill(swigCPtr, val);
  }

  public void clear() {
    micropolisenginePINVOKE.MapShort8_clear(swigCPtr);
  }

  public void set(int x, int y, short val) {
    micropolisenginePINVOKE.MapShort8_set(swigCPtr, x, y, val);
  }

  public short get(int x, int y) {
    short ret = micropolisenginePINVOKE.MapShort8_get(swigCPtr, x, y);
    return ret;
  }

  public bool onMap(int x, int y) {
    bool ret = micropolisenginePINVOKE.MapShort8_onMap(swigCPtr, x, y);
    return ret;
  }

  public void worldSet(int x, int y, short val) {
    micropolisenginePINVOKE.MapShort8_worldSet(swigCPtr, x, y, val);
  }

  public short worldGet(int x, int y) {
    short ret = micropolisenginePINVOKE.MapShort8_worldGet(swigCPtr, x, y);
    return ret;
  }

  public bool worldOnMap(int x, int y) {
    bool ret = micropolisenginePINVOKE.MapShort8_worldOnMap(swigCPtr, x, y);
    return ret;
  }

  public SWIGTYPE_p_short getBase() {
    IntPtr cPtr = micropolisenginePINVOKE.MapShort8_getBase(swigCPtr);
    SWIGTYPE_p_short ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_short(cPtr, false);
    return ret;
  }

}
