/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum SpriteType {
  SPRITE_NOTUSED = 0,
  SPRITE_TRAIN,
  SPRITE_HELICOPTER,
  SPRITE_AIRPLANE,
  SPRITE_SHIP,
  SPRITE_MONSTER,
  SPRITE_TORNADO,
  SPRITE_EXPLOSION,
  SPRITE_BUS,
  SPRITE_COUNT
}
