/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum Stri202 {
  STR202_POPULATIONDENSITY_LOW = 0,
  STR202_POPULATIONDENSITY_MEDIUM = 1,
  STR202_POPULATIONDENSITY_HIGH = 2,
  STR202_POPULATIONDENSITY_VERYHIGH = 3,
  STR202_LANDVALUE_SLUM = 4,
  STR202_LANDVALUE_LOWER_CLASS = 5,
  STR202_LANDVALUE_MIDDLE_CLASS = 6,
  STR202_LANDVALUE_HIGH_CLASS = 7,
  STR202_CRIME_NONE = 8,
  STR202_CRIME_LIGHT = 9,
  STR202_CRIME_MODERATE = 10,
  STR202_CRIME_DANGEROUS = 11,
  STR202_POLLUTION_NONE = 12,
  STR202_POLLUTION_MODERATE = 13,
  STR202_POLLUTION_HEAVY = 14,
  STR202_POLLUTION_VERY_HEAVY = 15,
  STR202_GROWRATE_DECLINING = 16,
  STR202_GROWRATE_STABLE = 17,
  STR202_GROWRATE_SLOWGROWTH = 18,
  STR202_GROWRATE_FASTGROWTH = 19
}
