/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum EditingTool {
  TOOL_RESIDENTIAL,
  TOOL_COMMERCIAL,
  TOOL_INDUSTRIAL,
  TOOL_FIRESTATION,
  TOOL_POLICESTATION,
  TOOL_QUERY,
  TOOL_WIRE,
  TOOL_BULLDOZER,
  TOOL_RAILROAD,
  TOOL_ROAD,
  TOOL_STADIUM,
  TOOL_PARK,
  TOOL_SEAPORT,
  TOOL_COALPOWER,
  TOOL_NUCLEARPOWER,
  TOOL_AIRPORT,
  TOOL_NETWORK,
  TOOL_WATER,
  TOOL_LAND,
  TOOL_FOREST,
  TOOL_COUNT,
  TOOL_FIRST = TOOL_RESIDENTIAL,
  TOOL_LAST = TOOL_FOREST
}
