/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MapType {
  MAP_TYPE_ALL,
  MAP_TYPE_RES,
  MAP_TYPE_COM,
  MAP_TYPE_IND,
  MAP_TYPE_POWER,
  MAP_TYPE_ROAD,
  MAP_TYPE_POPULATION_DENSITY,
  MAP_TYPE_RATE_OF_GROWTH,
  MAP_TYPE_TRAFFIC_DENSITY,
  MAP_TYPE_POLLUTION,
  MAP_TYPE_CRIME,
  MAP_TYPE_LAND_VALUE,
  MAP_TYPE_FIRE_RADIUS,
  MAP_TYPE_POLICE_RADIUS,
  MAP_TYPE_DYNAMIC,
  MAP_TYPE_COUNT
}
