/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class micropolisengine {
  public static int WORLD_W {
    get {
      int ret = micropolisenginePINVOKE.WORLD_W_get();
      return ret;
    } 
  }

  public static int WORLD_H {
    get {
      int ret = micropolisenginePINVOKE.WORLD_H_get();
      return ret;
    } 
  }

  public static int BITS_PER_TILE {
    get {
      int ret = micropolisenginePINVOKE.BITS_PER_TILE_get();
      return ret;
    } 
  }

  public static int BYTES_PER_TILE {
    get {
      int ret = micropolisenginePINVOKE.BYTES_PER_TILE_get();
      return ret;
    } 
  }

  public static int WORLD_W_2 {
    get {
      int ret = micropolisenginePINVOKE.WORLD_W_2_get();
      return ret;
    } 
  }

  public static int WORLD_H_2 {
    get {
      int ret = micropolisenginePINVOKE.WORLD_H_2_get();
      return ret;
    } 
  }

  public static int WORLD_W_4 {
    get {
      int ret = micropolisenginePINVOKE.WORLD_W_4_get();
      return ret;
    } 
  }

  public static int WORLD_H_4 {
    get {
      int ret = micropolisenginePINVOKE.WORLD_H_4_get();
      return ret;
    } 
  }

  public static int WORLD_W_8 {
    get {
      int ret = micropolisenginePINVOKE.WORLD_W_8_get();
      return ret;
    } 
  }

  public static int WORLD_H_8 {
    get {
      int ret = micropolisenginePINVOKE.WORLD_H_8_get();
      return ret;
    } 
  }

  public static int EDITOR_TILE_SIZE {
    get {
      int ret = micropolisenginePINVOKE.EDITOR_TILE_SIZE_get();
      return ret;
    } 
  }

  public static int PASSES_PER_CITYTIME {
    get {
      int ret = micropolisenginePINVOKE.PASSES_PER_CITYTIME_get();
      return ret;
    } 
  }

  public static int CITYTIMES_PER_MONTH {
    get {
      int ret = micropolisenginePINVOKE.CITYTIMES_PER_MONTH_get();
      return ret;
    } 
  }

  public static int CITYTIMES_PER_YEAR {
    get {
      int ret = micropolisenginePINVOKE.CITYTIMES_PER_YEAR_get();
      return ret;
    } 
  }

  public static int HISTORY_LENGTH {
    get {
      int ret = micropolisenginePINVOKE.HISTORY_LENGTH_get();
      return ret;
    } 
  }

  public static int MISC_HISTORY_LENGTH {
    get {
      int ret = micropolisenginePINVOKE.MISC_HISTORY_LENGTH_get();
      return ret;
    } 
  }

  public static int HISTORY_COUNT {
    get {
      int ret = micropolisenginePINVOKE.HISTORY_COUNT_get();
      return ret;
    } 
  }

  public static int POWER_STACK_SIZE {
    get {
      int ret = micropolisenginePINVOKE.POWER_STACK_SIZE_get();
      return ret;
    } 
  }

  public static int NOWHERE {
    get {
      int ret = micropolisenginePINVOKE.NOWHERE_get();
      return ret;
    } 
  }

  public static int MAX_TRAFFIC_DISTANCE {
    get {
      int ret = micropolisenginePINVOKE.MAX_TRAFFIC_DISTANCE_get();
      return ret;
    } 
  }

  public static int MAX_ROAD_EFFECT {
    get {
      int ret = micropolisenginePINVOKE.MAX_ROAD_EFFECT_get();
      return ret;
    } 
  }

  public static int MAX_POLICE_STATION_EFFECT {
    get {
      int ret = micropolisenginePINVOKE.MAX_POLICE_STATION_EFFECT_get();
      return ret;
    } 
  }

  public static int MAX_FIRE_STATION_EFFECT {
    get {
      int ret = micropolisenginePINVOKE.MAX_FIRE_STATION_EFFECT_get();
      return ret;
    } 
  }

  public static int RES_VALVE_RANGE {
    get {
      int ret = micropolisenginePINVOKE.RES_VALVE_RANGE_get();
      return ret;
    } 
  }

  public static int COM_VALVE_RANGE {
    get {
      int ret = micropolisenginePINVOKE.COM_VALVE_RANGE_get();
      return ret;
    } 
  }

  public static int IND_VALVE_RANGE {
    get {
      int ret = micropolisenginePINVOKE.IND_VALVE_RANGE_get();
      return ret;
    } 
  }

  public static void not_reached(int line, string fname) {
    micropolisenginePINVOKE.not_reached(line, fname);
  }

  public static int ISLAND_RADIUS {
    get {
      int ret = micropolisenginePINVOKE.ISLAND_RADIUS_get();
      return ret;
    } 
  }

  public static readonly int IS_INTEL = micropolisenginePINVOKE.IS_INTEL_get();
  public static readonly string MICROPOLIS_VERSION = micropolisenginePINVOKE.MICROPOLIS_VERSION_get();
}
