/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class StringTable : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StringTable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StringTable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StringTable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          micropolisenginePINVOKE.delete_StringTable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int id {
    set {
      micropolisenginePINVOKE.StringTable_id_set(swigCPtr, value);
    } 
    get {
      int ret = micropolisenginePINVOKE.StringTable_id_get(swigCPtr);
      return ret;
    } 
  }

  public int lines {
    set {
      micropolisenginePINVOKE.StringTable_lines_set(swigCPtr, value);
    } 
    get {
      int ret = micropolisenginePINVOKE.StringTable_lines_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_char strings {
    set {
      micropolisenginePINVOKE.StringTable_strings_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = micropolisenginePINVOKE.StringTable_strings_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public StringTable next {
    set {
      micropolisenginePINVOKE.StringTable_next_set(swigCPtr, StringTable.getCPtr(value));
    } 
    get {
      IntPtr cPtr = micropolisenginePINVOKE.StringTable_next_get(swigCPtr);
      StringTable ret = (cPtr == IntPtr.Zero) ? null : new StringTable(cPtr, false);
      return ret;
    } 
  }

  public StringTable() : this(micropolisenginePINVOKE.new_StringTable(), true) {
  }

}
