/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ToolResult {
  TOOLRESULT_NO_MONEY = -2,
  TOOLRESULT_NEED_BULLDOZE = -1,
  TOOLRESULT_FAILED = 0,
  TOOLRESULT_OK = 1
}
