/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MapTileBits {
  PWRBIT = 0x8000,
  CONDBIT = 0x4000,
  BURNBIT = 0x2000,
  BULLBIT = 0x1000,
  ANIMBIT = 0x0800,
  ZONEBIT = 0x0400,
  ALLBITS = ZONEBIT|ANIMBIT|BULLBIT|BURNBIT|CONDBIT|PWRBIT,
  LOMASK = 0x03ff,
  BLBNBIT = BULLBIT|BURNBIT,
  BLBNCNBIT = BULLBIT|BURNBIT|CONDBIT,
  BNCNBIT = BURNBIT|CONDBIT
}
