/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum Scenario {
  SC_NONE,
  SC_DULLSVILLE,
  SC_SAN_FRANCISCO,
  SC_HAMBURG,
  SC_BERN,
  SC_TOKYO,
  SC_DETROIT,
  SC_BOSTON,
  SC_RIO,
  SC_COUNT
}
