/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ZoneType {
  ZT_COMMERCIAL,
  ZT_INDUSTRIAL,
  ZT_RESIDENTIAL,
  ZT_NUM_DESTINATIONS
}
